### ISSUE TITLE
Address markup issues preventing correct rendering of API-level documentation

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/pycoal#176]
Hi @mjn0898 can you please take a look into why the following pages are not rendering correctly

https://pycoal.readthedocs.io/en/latest/conversion.html
https://pycoal.readthedocs.io/en/latest/mineral.html
https://pycoal.readthedocs.io/en/latest/mining.html
https://pycoal.readthedocs.io/en/latest/environment.html

Thanks

**Comment by mjn0898** [comment]
It looks like this issue is due to the following exceptions raised during the latest build:
![image](https://user-images.githubusercontent.com/24417929/67219609-32f8d100-f3dd-11e9-88fb-1cc654f7e44b.png)
Looking into fixing that issue now.
That screenshot is from https://readthedocs.org/api/v2/build/9834484.txt

**Comment by mjn0898** [comment]
That screenshot is from https://readthedocs.org/api/v2/build/9834484.txt

**Comment by mjn0898** [comment]
Update: Fixed the warnings, but the documentation is still not showing. If I look at the latest version of docs under downloads however, it is showing fine.

**Comment by lewismc** [comment]
@mjn0898 where is the pull request so I can see the code? Please push code early and push it often otherwise I cannot replicate anything.

**Comment by mjn0898** [comment]
@lewismc I created it: https://github.com/capstone-coal/pycoal/pull/180
I tried making changes that worked for other people that had the same issue such as https://github.com/ethereum/eth-account/issues/39, but that hasn't fixed the problem as of yet.

Also, I'm not sure if we need a pull request since it is not finalized, should i close that and just leave it on the separate branch?

**Comment by lewismc** [comment]
Fixed in #180
