### ISSUE TITLE
Add support for a progress bar when running the SAM algorithm 

### ISSUE THREAD

**Issue by Luner** [capstone-coal/pycoal#189]
Using the library [tqdm](https://pypi.org/project/tqdm/), we can create a progress bar when running through the SAM loop.  This would be useful as the runtime on large files is significant (potentially on the order of days), and seeing progress can be extremely helpful when determining whether or not to prematurely exit the process.

**Comment by lewismc** [comment]
@mjn0898 please take this issue on. If you need assistance with it then ask @Luner .
Thank you both.

**Comment by lewismc** [comment]
@mjn0898 please start work on this issue. Thanks

**Comment by mjn0898** [comment]
Sounds good.

**Comment by mjn0898** [comment]
After discussion with the team today, it seems tqdm can be used to display a progress bar for SAM_serial only, not the other implementations due to the way the loops are set up. I just want to confirm that we still want this implemented for just the one implementation. If so, it should be a rather simple change to the code in the SAM_serial function once ISSUE196 pr is merged.

**Comment by lewismc** [comment]
No don't bother implementing it. Let's close for now. Please address the comment I left for you in #198
