### ISSUE TITLE
Tests for mineral classification

### ISSUE THREAD

**Issue by heidiaclayton** [capstone-coal/pycoal#36]
I'll be writing tests using nosetests for the mineral classification functionality. I may need to make revisions in the code (e.g. the neural network structure) to make the tests pass.

**Comment by ghost** [comment]
@heidiaclayton @lewismc it would be helpful to have tests for the current revision of the mineral classifier so that we know what effect changes to the algorithm or the spectral library will have. i recommend slicing out one or more representative 10x10 pixel regions of the original san juan flightline and saving them as subimages in the test directory. the test could verify the classification of each pixel so that we can see if anything changes when we change the implementation. i'm not sure of the best way to handle file i/o in python unit tests. maybe write the output to `/tmp`?

**Comment by ghost** [comment]
@heidiaclayton  you'll want to merge or rebase onto the latest version of `master` which contains a number of changes including several tests of the other methods. or let me know if you'd like to trade for any of my issues.

**Comment by ghost** [comment]
i'm going to go ahead and close this since it has been merged into `development`.
