### ISSUE TITLE
Implement application logging 

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/pycoal#46]
We should begin to use a logging facility which will enable us to write application logs to file. We can start with
https://docs.python.org/3/library/logging.html

**Comment by ghost** [comment]
in addition to running time (issue https://github.com/capstone-coal/pycoal/issues/47), a useful thing to log would be which pycoal version was executed, particularly if it contained the specific git revision and any changes in the working directory. it would also be possible to store this data in the header file.

**Comment by ghost** [comment]
since the mineral classification takes such a long time and is generally run in the background, note that logging to a file would probably be preferable to standard output.

one possibility would be to make the mineral classifier constructor take an optional `logFile=None` parameter which, if provided, would enable logging to a file.

if i find an easy way to do this while i am [processing the imagery](https://github.com/capstone-coal/pycoal/issues/49), i may be able to help with this issue.

the running time is the most significant thing i care about right now in terms of performance.

**Comment by ghost** [comment]
as mentioned in issue https://github.com/capstone-coal/pycoal/issues/49, we might also like to have a progress meter to help show relative completion. nothing interactive, just log completion in intervals of 10% perhaps. this might have a negative effect in terms of performance, so it would need to be implemented carefully.

**Comment by ghost** [comment]
possible constructor parameter: `logFile=sys.stdout`

here's a logging howto: https://docs.python.org/2/howto/logging.html

**Comment by ghost** [comment]
my processing [script](https://github.com/capstone-coal/pycoal/issues/49#issuecomment-292422497) currently implements rudimentary logging by hand. unassigning self while i focus on higher priority issues. this issue could be put off to a later milestone when the code is more mature. note that the static methods would need to be made into instance methods if logging is handled by the class constructor.

**Comment by lewismc** [comment]
I am baking this in to #113 and it is working beautifully.

**Comment by lewismc** [comment]
Implemented in https://github.com/capstone-coal/pycoal/pull/113
