### ISSUE TITLE
Implement timeit for measuring execution of core tasks

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/pycoal#47]
We've been talking about execution times for various classification tasks. Once we have logging implemented, we should use https://docs.python.org/2/library/timeit.html to write out execution times to file.

**Comment by ghost** [comment]
@lewismc is `timeit()` appropriate for profiling production code, or is this something we'd want to implement for testing only?

the end user cares how long it takes to classify a full image, but maybe not how many milliseconds it takes to resample bands or calculate spectral angles for each pixel. in the [processing](https://github.com/capstone-coal/pycoal/issues/49) issue i have just been logging timestamps for that purpose.

on the other hand, we might like to get some hard data on what parts of the [algorithm](https://github.com/capstone-coal/pycoal/blob/master/pycoal/mineral.py) are taking longest. since `timeit()` evaluates strings as code, we could gather sample data by running interesting sections by hand. alternatively, we might be able to find a way to do profiling conditionally or add [unit tests](https://github.com/capstone-coal/pycoal/issues/36) to measure the relative costs of functions called by the classifier.

my reading of the spectral [documentation](http://www.spectralpython.net/fileio.html#loading-entire-images) and investigation in the [performance](https://github.com/capstone-coal/pycoal/issues/51) issue suggests that the file I/O and the spectral angle mapper are the costliest operations. we might consider making this part of that issue which is in milestone 0.3.

**Comment by ghost** [comment]
reference to @heidiaclayton's previous [discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/coal-capstone/5MzGiE1qZYk/49DVyWRODQAJ) on cprofile.

**Comment by lewismc** [comment]
Implemented in https://github.com/capstone-coal/pycoal/pull/113
